<?php

/**
 * Implements hook_menu().
 */
function screen_keyboard_menu() {
  $items = array();
  $items['admin/config/user-interface/screen-keyboard'] = array(
    'title' => 'Screen keyboard',
    'description' => 'Attach a on-screen keyboard to a text fields for mouse-driven entry.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('screen_keyboard_admin_settings'),
    'access arguments' => array('administer screen keyboard'),
    'file' => 'screen_keyboard.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function screen_keyboard_permission() {
  return array(
    'administer screen keyboard' => array(
      'title' => t('Administer screen keyboard settings'),
    ),
    'use screen keyboard' => array(
      'title' => t('Use screen keyboard'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function screen_keyboard_libraries_info() {
  $libraries['jquery.keyboard'] = array(
    'title' => 'jQuery Virtual Keyboard',
    'vendor url' => 'https://github.com/Mottie/Keyboard',
    'download url' => 'https://github.com/Mottie/Keyboard/archive/master.zip',
    'files' => array(
      'js' => array(
        'js/jquery.keyboard.min.js',
      ),
      'css' => array(
        'css/keyboard.css',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_element_info_alter().
 */
function screen_keyboard_element_info_alter(&$types) {
  foreach (array_keys($types) as $type) {
    switch ($type) {
      case 'form':
      case 'textarea':
      case 'textfield':
        $types[$type]['#process'][] = 'screen_keyboard_process_element';
        break;
    }
  }
}

/**
 * Element process callback.
 *
 * @param array $element
 *   The render array element.
 *
 * @return array
 *   The processed element.
 */
function screen_keyboard_process_element($element) {
  if (isset($element['#screen_keyboard'])) {
    $action = $element['#screen_keyboard'] == TRUE ? 'include' : 'exclude';
    if ($element['#type'] == 'form') {
      $element['#attributes']['class'][] = 'screen-keyboard-' . $action . '-children';
    }
    else {
      $element['#attributes']['class'][] = 'screen-keyboard-' . $action;
    }
  }
  if ($element['#type'] == 'form') {
    screen_keyboard_attach($element);
  }
  return $element;
}

/**
 * Adds screen keyboard support to form element.
 * 
 * @param array $element
 *   Form API element.
 */
function screen_keyboard_attach(&$element) {
  // Adding Virtual Keyboard plugin library.
  if (!module_exists('libraries') || !libraries_detect('jquery.keyboard')) {
    return;
  }

  $element['#attached']['library'][] = array('system', 'ui');
  $element['#attached']['library'][] = array('system', 'ui.position');
  $element['#attached']['libraries_load'][] = array('jquery.keyboard');

  // Adding settings.
  $whitechars = array("\r\n", "\r", "\n");
  $element['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array(
      'screen_keyboard' => array(
        'include' => str_replace($whitechars, ',', variable_get('screen_keyboard_include', '')),
        'exclude' => str_replace($whitechars, ',', variable_get('screen_keyboard_exclude', '')),
      ),
    ),
  );
  // Adding module JS file.
  $element['#attached']['js'][] = array(
    'type' => 'file',
    'data' => drupal_get_path('module', 'screen_keyboard') . '/screen_keyboard.js',
  );
  // Adding module CSS file.
  $element['#attached']['css'][] = array(
    'type' => 'file',
    'data' => drupal_get_path('module', 'screen_keyboard') . '/screen_keyboard.css',
  );
}
